// GENERATED BY CODE! DO NOT MODIFY!
using UnityEngine;
namespace Watermelon
{
	[System.Serializable]
	public class Sounds
	{
		public AudioClip tileClick;
		public AudioClip tileClickBlocked;
		public AudioClip mergeSound;

		public AudioClip iceCrackSound;
		public AudioClip crateCrackSound;
		public AudioClip rubberSound;

		public AudioClip levelComplete;
		public AudioClip levelFailed;

		[LineSpacer("UI")]
		public AudioClip buttonSound;
	}
}